//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialCrmDBEntities : DbContext
    {
        public FinancialCrmDBEntities()
            : base("name=FinancialCrmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_BANK> TBL_BANK { get; set; }
        public virtual DbSet<TBL_BILL> TBL_BILL { get; set; }
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual DbSet<TBL_PROCESS> TBL_PROCESS { get; set; }
        public virtual DbSet<TBL_SPENDING> TBL_SPENDING { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
    }
}
